### ISSUE TITLE
apiVersion issue when trying on k8s cluster v1.8.x

### ISSUE THREAD

**Issue by ishantanu** [kubernauts/kafka-confluent-platform#1]
Hi,

While the setup works perfectly fine for k8s version 1.9+, when I tried the setup with v1.8.x, it shows an error:
```
Error from server (BadRequest): StatefulSet in version "v1" cannot be handled as a StatefulSet: no kind "StatefulSet" is registered for version "apps/v1"
```

Which is correct, since, in v1.8 the `apiversion` should be `apps/v1beta2` instead of `apps/v1`.

Possible ways to address this situation:
1. Add prerequisites in the documentation specifying the minimum k8s version.
2. Create a separate branch for addressing the issue, change the `apiVersion` and add this in the documentation.

This totally depends on **if** there is a plan to support `k8s < 1.9.x`. In either case, adding a simple prerequisites for this might be a good idea.

More info, [k8s-1.8-documentation](https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/statefulset/).

**Comment by arashkaffamanesh** [comment]
Thanks for the nice hint, yes we're aware about this issue, the whole thing was developed and tested on EKS with k8s 1.10.3, with tk8 made k8s 1.11.2 and OpenShift 3.5 and 3.7. We'll add this as prerequisite to the final documentation.

**Comment by ishantanu** [comment]
As the prerequisites are added in documentation, this can be closed. Thanks.
